### ISSUE TITLE
Invalid path.join in player.py

### ISSUE THREAD

**Issue by djkool** [sam0s/dungeon-farm#11]
This backtrace occurs on non-Windows machines:
```
Traceback (most recent call last):
  File "dungeon new.py", line 21, in <module>
    GAME=game.Game(screen)
  File ".../dungeon-farm/gameData/assets/game.py", line 37, in __init__
    self.player=player.Player(384.0,224.0,self.gw)
  File ".../dungeon-farm/gameData/assets/player.py", line 53, in __init__
    self.player_anim = AnimationSet(path.join("images\player_14.png"), (16, 24))
  File ".../dungeon-farm/gameData/assets/gamelib.py", line 75, in __init__
    TileSet.__init__(self, filename, tile_size)
  File ".../dungeon-farm/gameData/assets/gamelib.py", line 25, in __init__
    self.image = pg.image.load(filename)
pygame.error: Couldn't open images\player_14.png
```
It looks like one of the assets paths were not properly converted to use `path.join`. Easy fix:
```
--- a/gameData/assets/player.py
+++ b/gameData/assets/player.py
@@ -50,7 +50,7 @@ class Player(object):
         self.maxhp=100
 
 
-        self.player_anim = AnimationSet(path.join("images\player_14.png"), (16, 24))
+        self.player_anim = AnimationSet(path.join("images", "player_14.png"), (16, 24))
         self.player_anim.addAnim("walk_down", 0, 3)
         self.player_anim.addAnim("walk_right", 4, 7)
         self.player_anim.addAnim("walk_left", 8, 11)
```

**Comment by sam0s** [comment]
Thanks for finding that!

**Comment by sam0s** [comment]
fixed
