### ISSUE TITLE
Crash on player death.

### ISSUE THREAD

**Issue by djkool** [sam0s/dungeon-farm#12]
Game will crash is player health drops below 0:
```
Traceback (most recent call last):
  File "dungeon new.py", line 26, in <module>
    main2()
  File "dungeon new.py", line 21, in main2
    GAME.Update(dt=float(timer.tick(100)*1e-3))
  File "~/dungeon-farm/gameData/assets/game.py", line 61, in Update
    self.gw.Update(dt)
  File "~/dungeon-farm/gameData/assets/world.py", line 132, in Update
    self.bat.Draw()
  File "~/dungeon-farm/gameData/assets/battle.py", line 96, in Draw
    self.Attack()
  File "~/dungeon-farm/gameData/assets/battle.py", line 73, in Attack
    self.world.game.ChangeState("menu")
AttributeError: 'Game' object has no attribute 'ChangeState'
```

Another easy fix:
```
--- a/gameData/assets/battle.py
+++ b/gameData/assets/battle.py
@@ -70,7 +70,7 @@ class Battle(object):
 
         #test player death
         if self.world.player.hp<=0:
-            self.world.game.ChangeState("menu")
+            self.world.ChangeState("menu")
```

**Comment by sam0s** [comment]
fixed!
